//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل وجود {0} امکان حذف وجود ندارد..
        /// </summary>
        internal static string DeleteError_ExistEntity {
            get {
                return ResourceManager.GetString("DeleteError_ExistEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد وصولی تکراری در فایل اکسل .
        /// </summary>
        internal static string ExcelError_DuplicateRecord {
            get {
                return ResourceManager.GetString("ExcelError_DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سطر {0} و ستون {1}  رخ داده است.{2}.
        /// </summary>
        internal static string ExcelError_Existence {
            get {
                return ResourceManager.GetString("ExcelError_Existence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ فایلی بارگزاری نشده است. لطفا ابتدا فایل موردنظر را بارگزاری کنید..
        /// </summary>
        internal static string ExcelError_FileNotUploaded {
            get {
                return ResourceManager.GetString("ExcelError_FileNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ های قبل از سال 94 مجاز نیستند..
        /// </summary>
        internal static string ExcelError_InvalidDate {
            get {
                return ResourceManager.GetString("ExcelError_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سطر {0} و ستون {1}  رخ داده است. اطلاعات {2} معتبر نیست..
        /// </summary>
        internal static string ExcelError_Validate {
            get {
                return ResourceManager.GetString("ExcelError_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تکمیل نشده است.
        /// </summary>
        internal static string InformationNotCompelete {
            get {
                return ResourceManager.GetString("InformationNotCompelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما غیر مجاز می باشد..
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ {0} انتخاب نشده است..
        /// </summary>
        internal static string NoSelectedEntity {
            get {
                return ResourceManager.GetString("NoSelectedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مشخص نیست..
        /// </summary>
        internal static string NoSpecified {
            get {
                return ResourceManager.GetString("NoSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای {0} مقدار صحیح وارد نشده است.
        /// </summary>
        internal static string NotInRange {
            get {
                return ResourceManager.GetString("NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن {0} اجباری می باشد.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره سازی با خطا مواجه شد.
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} صحیح نمی باشد..
        /// </summary>
        internal static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
    }
}
