//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditBrokerMvc.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalcHelper.UserDataCr24SvcModel", Namespace="http://schemas.datacontract.org/2004/07/CreditBroker.Helper")]
    [System.SerializableAttribute()]
    public partial class CalcHelperUserDataCr24SvcModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFaFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFaFullName {
            get {
                return this.UserFaFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFaFullNameField, value) != true)) {
                    this.UserFaFullNameField = value;
                    this.RaisePropertyChanged("UserFaFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestModel", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class RequestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditBrokerMvc.ServiceReference1.BrokerPerformanceVariables BrokerPerformanceVariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditBrokerMvc.ServiceReference1.BusinessVaribales BusinessVaribalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditBrokerMvc.ServiceReference1.CreditCompanyAndManager CreditCompanyAndManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditBrokerMvc.ServiceReference1.FinancialRatio FinancialRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditBrokerMvc.ServiceReference1.BrokerPerformanceVariables BrokerPerformanceVariables {
            get {
                return this.BrokerPerformanceVariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerPerformanceVariablesField, value) != true)) {
                    this.BrokerPerformanceVariablesField = value;
                    this.RaisePropertyChanged("BrokerPerformanceVariables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditBrokerMvc.ServiceReference1.BusinessVaribales BusinessVaribales {
            get {
                return this.BusinessVaribalesField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessVaribalesField, value) != true)) {
                    this.BusinessVaribalesField = value;
                    this.RaisePropertyChanged("BusinessVaribales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyNationalCode {
            get {
                return this.CompanyNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNationalCodeField, value) != true)) {
                    this.CompanyNationalCodeField = value;
                    this.RaisePropertyChanged("CompanyNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditBrokerMvc.ServiceReference1.CreditCompanyAndManager CreditCompanyAndManager {
            get {
                return this.CreditCompanyAndManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCompanyAndManagerField, value) != true)) {
                    this.CreditCompanyAndManagerField = value;
                    this.RaisePropertyChanged("CreditCompanyAndManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditBrokerMvc.ServiceReference1.FinancialRatio FinancialRatio {
            get {
                return this.FinancialRatioField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialRatioField, value) != true)) {
                    this.FinancialRatioField = value;
                    this.RaisePropertyChanged("FinancialRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerPerformanceVariables", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class BrokerPerformanceVariables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AmountOfValueAtRiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short BrokerRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EmtiazCommitteePayeshRiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LastYearIncomeReportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MojavezMoamelatKalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MojavezSabadGardaniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPersonnelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfbranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PreviousLastYearIncomeReportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SarmayehSabtiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SumOfFacilityToCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SumOfReceiveFacilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TarkibSahamdaranField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AmountOfValueAtRisk {
            get {
                return this.AmountOfValueAtRiskField;
            }
            set {
                if ((this.AmountOfValueAtRiskField.Equals(value) != true)) {
                    this.AmountOfValueAtRiskField = value;
                    this.RaisePropertyChanged("AmountOfValueAtRisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short BrokerRank {
            get {
                return this.BrokerRankField;
            }
            set {
                if ((this.BrokerRankField.Equals(value) != true)) {
                    this.BrokerRankField = value;
                    this.RaisePropertyChanged("BrokerRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EmtiazCommitteePayeshRisk {
            get {
                return this.EmtiazCommitteePayeshRiskField;
            }
            set {
                if ((this.EmtiazCommitteePayeshRiskField.Equals(value) != true)) {
                    this.EmtiazCommitteePayeshRiskField = value;
                    this.RaisePropertyChanged("EmtiazCommitteePayeshRisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LastYearIncomeReported {
            get {
                return this.LastYearIncomeReportedField;
            }
            set {
                if ((this.LastYearIncomeReportedField.Equals(value) != true)) {
                    this.LastYearIncomeReportedField = value;
                    this.RaisePropertyChanged("LastYearIncomeReported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MojavezMoamelatKala {
            get {
                return this.MojavezMoamelatKalaField;
            }
            set {
                if ((this.MojavezMoamelatKalaField.Equals(value) != true)) {
                    this.MojavezMoamelatKalaField = value;
                    this.RaisePropertyChanged("MojavezMoamelatKala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MojavezSabadGardani {
            get {
                return this.MojavezSabadGardaniField;
            }
            set {
                if ((this.MojavezSabadGardaniField.Equals(value) != true)) {
                    this.MojavezSabadGardaniField = value;
                    this.RaisePropertyChanged("MojavezSabadGardani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPersonnel {
            get {
                return this.NumberOfPersonnelField;
            }
            set {
                if ((this.NumberOfPersonnelField.Equals(value) != true)) {
                    this.NumberOfPersonnelField = value;
                    this.RaisePropertyChanged("NumberOfPersonnel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfbranch {
            get {
                return this.NumberOfbranchField;
            }
            set {
                if ((this.NumberOfbranchField.Equals(value) != true)) {
                    this.NumberOfbranchField = value;
                    this.RaisePropertyChanged("NumberOfbranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PreviousLastYearIncomeReported {
            get {
                return this.PreviousLastYearIncomeReportedField;
            }
            set {
                if ((this.PreviousLastYearIncomeReportedField.Equals(value) != true)) {
                    this.PreviousLastYearIncomeReportedField = value;
                    this.RaisePropertyChanged("PreviousLastYearIncomeReported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SarmayehSabti {
            get {
                return this.SarmayehSabtiField;
            }
            set {
                if ((this.SarmayehSabtiField.Equals(value) != true)) {
                    this.SarmayehSabtiField = value;
                    this.RaisePropertyChanged("SarmayehSabti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SumOfFacilityToCustomer {
            get {
                return this.SumOfFacilityToCustomerField;
            }
            set {
                if ((this.SumOfFacilityToCustomerField.Equals(value) != true)) {
                    this.SumOfFacilityToCustomerField = value;
                    this.RaisePropertyChanged("SumOfFacilityToCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SumOfReceiveFacility {
            get {
                return this.SumOfReceiveFacilityField;
            }
            set {
                if ((this.SumOfReceiveFacilityField.Equals(value) != true)) {
                    this.SumOfReceiveFacilityField = value;
                    this.RaisePropertyChanged("SumOfReceiveFacility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TarkibSahamdaran {
            get {
                return this.TarkibSahamdaranField;
            }
            set {
                if ((this.TarkibSahamdaranField.Equals(value) != true)) {
                    this.TarkibSahamdaranField = value;
                    this.RaisePropertyChanged("TarkibSahamdaran");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessVaribales", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class BusinessVaribales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CompanyActivityTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EducationLevelOfManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExperinceOfManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OwnerShipOfLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RelatedEducationOfManagerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CompanyActivityTime {
            get {
                return this.CompanyActivityTimeField;
            }
            set {
                if ((this.CompanyActivityTimeField.Equals(value) != true)) {
                    this.CompanyActivityTimeField = value;
                    this.RaisePropertyChanged("CompanyActivityTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EducationLevelOfManager {
            get {
                return this.EducationLevelOfManagerField;
            }
            set {
                if ((this.EducationLevelOfManagerField.Equals(value) != true)) {
                    this.EducationLevelOfManagerField = value;
                    this.RaisePropertyChanged("EducationLevelOfManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExperinceOfManager {
            get {
                return this.ExperinceOfManagerField;
            }
            set {
                if ((this.ExperinceOfManagerField.Equals(value) != true)) {
                    this.ExperinceOfManagerField = value;
                    this.RaisePropertyChanged("ExperinceOfManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OwnerShipOfLocation {
            get {
                return this.OwnerShipOfLocationField;
            }
            set {
                if ((this.OwnerShipOfLocationField.Equals(value) != true)) {
                    this.OwnerShipOfLocationField = value;
                    this.RaisePropertyChanged("OwnerShipOfLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RelatedEducationOfManager {
            get {
                return this.RelatedEducationOfManagerField;
            }
            set {
                if ((this.RelatedEducationOfManagerField.Equals(value) != true)) {
                    this.RelatedEducationOfManagerField = value;
                    this.RaisePropertyChanged("RelatedEducationOfManager");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCompanyAndManager", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class CreditCompanyAndManager : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerNationalCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerNationalCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerNationalCode3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyScore {
            get {
                return this.CompanyScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyScoreField, value) != true)) {
                    this.CompanyScoreField = value;
                    this.RaisePropertyChanged("CompanyScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerNationalCode1 {
            get {
                return this.ManagerNationalCode1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerNationalCode1Field, value) != true)) {
                    this.ManagerNationalCode1Field = value;
                    this.RaisePropertyChanged("ManagerNationalCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerNationalCode2 {
            get {
                return this.ManagerNationalCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerNationalCode2Field, value) != true)) {
                    this.ManagerNationalCode2Field = value;
                    this.RaisePropertyChanged("ManagerNationalCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerNationalCode3 {
            get {
                return this.ManagerNationalCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerNationalCode3Field, value) != true)) {
                    this.ManagerNationalCode3Field = value;
                    this.RaisePropertyChanged("ManagerNationalCode3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialRatio", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class FinancialRatio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EzharHesabresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FinancialCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HoghogheSahebanSahamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NetProfitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SumDaraeiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SumDaramadAmaliatyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalDebtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EzharHesabres {
            get {
                return this.EzharHesabresField;
            }
            set {
                if ((this.EzharHesabresField.Equals(value) != true)) {
                    this.EzharHesabresField = value;
                    this.RaisePropertyChanged("EzharHesabres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FinancialCost {
            get {
                return this.FinancialCostField;
            }
            set {
                if ((this.FinancialCostField.Equals(value) != true)) {
                    this.FinancialCostField = value;
                    this.RaisePropertyChanged("FinancialCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HoghogheSahebanSaham {
            get {
                return this.HoghogheSahebanSahamField;
            }
            set {
                if ((this.HoghogheSahebanSahamField.Equals(value) != true)) {
                    this.HoghogheSahebanSahamField = value;
                    this.RaisePropertyChanged("HoghogheSahebanSaham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NetProfit {
            get {
                return this.NetProfitField;
            }
            set {
                if ((this.NetProfitField.Equals(value) != true)) {
                    this.NetProfitField = value;
                    this.RaisePropertyChanged("NetProfit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SumDaraei {
            get {
                return this.SumDaraeiField;
            }
            set {
                if ((this.SumDaraeiField.Equals(value) != true)) {
                    this.SumDaraeiField = value;
                    this.RaisePropertyChanged("SumDaraei");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SumDaramadAmaliaty {
            get {
                return this.SumDaramadAmaliatyField;
            }
            set {
                if ((this.SumDaramadAmaliatyField.Equals(value) != true)) {
                    this.SumDaramadAmaliatyField = value;
                    this.RaisePropertyChanged("SumDaramadAmaliaty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalDebt {
            get {
                return this.TotalDebtField;
            }
            set {
                if ((this.TotalDebtField.Equals(value) != true)) {
                    this.TotalDebtField = value;
                    this.RaisePropertyChanged("TotalDebt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultModel", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class ResultModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditBrokerMvc.ServiceReference1.CreditBrokerModel[] CreditBrokerModelListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsServiceOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyNationalCode {
            get {
                return this.CompanyNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNationalCodeField, value) != true)) {
                    this.CompanyNationalCodeField = value;
                    this.RaisePropertyChanged("CompanyNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditBrokerMvc.ServiceReference1.CreditBrokerModel[] CreditBrokerModelList {
            get {
                return this.CreditBrokerModelListField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditBrokerModelListField, value) != true)) {
                    this.CreditBrokerModelListField = value;
                    this.RaisePropertyChanged("CreditBrokerModelList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsServiceOk {
            get {
                return this.IsServiceOkField;
            }
            set {
                if ((this.IsServiceOkField.Equals(value) != true)) {
                    this.IsServiceOkField = value;
                    this.RaisePropertyChanged("IsServiceOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalScore {
            get {
                return this.TotalScoreField;
            }
            set {
                if ((this.TotalScoreField.Equals(value) != true)) {
                    this.TotalScoreField = value;
                    this.RaisePropertyChanged("TotalScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditBrokerModel", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class CreditBrokerModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SumScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreditBrokerMvc.ServiceReference1.Status[] statusesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditName {
            get {
                return this.CreditNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditNameField, value) != true)) {
                    this.CreditNameField = value;
                    this.RaisePropertyChanged("CreditName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SumScore {
            get {
                return this.SumScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.SumScoreField, value) != true)) {
                    this.SumScoreField = value;
                    this.RaisePropertyChanged("SumScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreditBrokerMvc.ServiceReference1.Status[] statuses {
            get {
                return this.statusesField;
            }
            set {
                if ((object.ReferenceEquals(this.statusesField, value) != true)) {
                    this.statusesField = value;
                    this.RaisePropertyChanged("statuses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/CreditBrokerWCF.Models")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoreValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScoreValue {
            get {
                return this.ScoreValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreValueField, value) != true)) {
                    this.ScoreValueField = value;
                    this.RaisePropertyChanged("ScoreValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBrokerServices")]
    public interface IBrokerServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServices/GetUserData", ReplyAction="http://tempuri.org/IBrokerServices/GetUserDataResponse")]
        CreditBrokerMvc.ServiceReference1.CalcHelperUserDataCr24SvcModel GetUserData(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServices/GetUserData", ReplyAction="http://tempuri.org/IBrokerServices/GetUserDataResponse")]
        System.Threading.Tasks.Task<CreditBrokerMvc.ServiceReference1.CalcHelperUserDataCr24SvcModel> GetUserDataAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServices/Credit", ReplyAction="http://tempuri.org/IBrokerServices/CreditResponse")]
        CreditBrokerMvc.ServiceReference1.ResultModel Credit(CreditBrokerMvc.ServiceReference1.RequestModel value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServices/Credit", ReplyAction="http://tempuri.org/IBrokerServices/CreditResponse")]
        System.Threading.Tasks.Task<CreditBrokerMvc.ServiceReference1.ResultModel> CreditAsync(CreditBrokerMvc.ServiceReference1.RequestModel value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServices/CheckCreditToday", ReplyAction="http://tempuri.org/IBrokerServices/CheckCreditTodayResponse")]
        CreditBrokerMvc.ServiceReference1.ResultModel CheckCreditToday(string companyNationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServices/CheckCreditToday", ReplyAction="http://tempuri.org/IBrokerServices/CheckCreditTodayResponse")]
        System.Threading.Tasks.Task<CreditBrokerMvc.ServiceReference1.ResultModel> CheckCreditTodayAsync(string companyNationalCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerServicesChannel : CreditBrokerMvc.ServiceReference1.IBrokerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerServicesClient : System.ServiceModel.ClientBase<CreditBrokerMvc.ServiceReference1.IBrokerServices>, CreditBrokerMvc.ServiceReference1.IBrokerServices {
        
        public BrokerServicesClient() {
        }
        
        public BrokerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrokerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CreditBrokerMvc.ServiceReference1.CalcHelperUserDataCr24SvcModel GetUserData(string userName) {
            return base.Channel.GetUserData(userName);
        }
        
        public System.Threading.Tasks.Task<CreditBrokerMvc.ServiceReference1.CalcHelperUserDataCr24SvcModel> GetUserDataAsync(string userName) {
            return base.Channel.GetUserDataAsync(userName);
        }
        
        public CreditBrokerMvc.ServiceReference1.ResultModel Credit(CreditBrokerMvc.ServiceReference1.RequestModel value) {
            return base.Channel.Credit(value);
        }
        
        public System.Threading.Tasks.Task<CreditBrokerMvc.ServiceReference1.ResultModel> CreditAsync(CreditBrokerMvc.ServiceReference1.RequestModel value) {
            return base.Channel.CreditAsync(value);
        }
        
        public CreditBrokerMvc.ServiceReference1.ResultModel CheckCreditToday(string companyNationalCode) {
            return base.Channel.CheckCreditToday(companyNationalCode);
        }
        
        public System.Threading.Tasks.Task<CreditBrokerMvc.ServiceReference1.ResultModel> CheckCreditTodayAsync(string companyNationalCode) {
            return base.Channel.CheckCreditTodayAsync(companyNationalCode);
        }
    }
}
